INSERT INTO `transformadores`.`preguntas` 
(`id_pregunta`, `pregunta`, `comentarios`, `requerida`, `id_pregunta_dependiente`, `id_tipo`, `id_grupo`, `id_lenguaje`)
VALUES 
('1', 'Nombre de la experiencia postulada', '', '1', '1', '1', '1', '1'),
('2', 'Organización postulante', '', '1', '2', '1', '1', '1'),
('3', 'Nombre del postulante', '', '1', '3', '2', '1', '1'),
('4', 'Teléfono de contacto', '', '1', '4', '2', '1', '1'),
('5', 'Email de contacto', '', '1', '5', '2', '1', '1'),
('6', 'País', '', '1', '6', '4', '1', '1'),
('7', 'Municipio', '', '1', '7', '2', '1', '1'),
('8', 'Localización', '', '1', '8', '3', '1', '1'),
('9', 'Estado actual', '', '1', '9', '3', '1', '1'),
('10', 'Fecha de inicio', '', '1', '10', '5', '1', '1'),
('11', 'Nombre de las organizaciones que participan en la experiencia', '', '1', '11', '1', '1', '1'),
('12', 'Naturaleza de las organizaciones que participan en la experiencia', '', '1', '12', '1', '1', '1'),
('13', '¿Por qué nació esta experiencia?', '', '1', '13', '1', '2', '1'),
('14', '¿Qué problema busca(ó) resolver?', '', '1', '14', '1', '2', '1'),
('15', '¿Cuáles son las causas que generan(on) este problema?', '', '1', '15', '1', '2', '1'),
('16', '¿Cuáles son los efectos – consecuencias derivadas por este problema?', '', '1', '16', '1', '2', '1'),
('17', 'Suministre información y datos que permitan conocer el entorno, el territorio y el perfil de la comunidad donde ocurre la experiencia', '', '1', '17', '1', '2', '1'),
('18', '¿Cuáles son (fueron) los principales objetivos de la experiencia?', '', '1', '18', '1', '2', '1'),
('19', '¿A quién está(estuvo) dirigida la acción? Quiénes se benefician(ron) de esta experiencia?', '', '1', '19', '1', '2', '1'),
('20', '¿Cuál es(fue) el monto aproximado de inversión realizada en esta experiencia y quiénes son(fueron) los aportantes?', '', '1', '20', '1', '2', '1'),
('21', '¿Cuáles son(fueron) las principales fases y actividades realizadas para el desarrollo de esta experiencia', '', '1', '21', '1', '2', '1'),
('22', '¿Qué aspectos de la experiencia considera innovadores para el contexto en el que se desarrolla(ó) y por qué?', '', '1', '22', '1', '3', '1'),
('23', '¿Qué aprendizajes derivados de la experiencia considera que pueden ser de utilidad y potencialmente transferibles a otras organizaciones y contextos que enfrentan retos similares?', '', '1', '23', '1', '3', '1'),
('24', 'Mencione tres datos o hechos que permiten evidenciar que los efectos positivos generados a partir de la experiencia, serán duraderos y permitirán a la comunidad enfrentar de mejor manera nuevos desafíos', '', '1', '24', '1', '3', '1'),
('25', '¿La experiencia amplía (ó) la participación de la comunidad?', 'Califique de 1 a 5 (siendo 1 la menor y 5 la mayor)', '1', '25', '3', '6', '1'),
('26', 'Explique su respuesta', '', '1', '25', '1', '6', '1'),
('27', '¿En qué etapas del proceso participa(ó) la comunidad (diseño, ejecución, seguimiento, etc.)?', '¿Cómo participa(ó)?', '1', '27', '1', '6', '1'),
('28', '¿Qué responsabilidades asume(ió) la comunidad en esta experiencia?', '', '1', '28', '1', '6', '1'),
('29', '¿Cuál es(fue) el papel de la comunidad en esta experiencia (cooperación, seguimiento, deliberación, ejecución, otro)?', '', '1', '29', '1', '6', '1'),
('30', '¿Cuál es(fue) el papel del miembro de RedEAmérica en la experiencia?', '', '1', '30', '1', '6', '1'),
('31', 'La experiencia amplia(ó) el acceso, administración y control de recursos por parte de la comunidad?', 'Califique de 1 a 5 (siendo 1 la menor y 5 la mayor)', '1', '31', '3', '6', '1'),
('32', 'Explique su respuesta', '', '1', '31', '1', '6', '1'),
('33', 'La experiencia contribuye(ó) a construir y/o ampliar los espacios de participación pública para la comunidad?', 'Califique de 1 a 5 (siendo 1 la menor y 5 la mayor)', '1', '33', '3', '7', '1'),
('34', 'Explique su respuesta', '', '1', '33', '1', '7', '1'),
('35', 'La experiencia influye(ó) en el diseño de políticas, programas y medidas del gobierno?', 'Califique de 1 a 5 (siendo 1 la menor y 5 la mayor)', '1', '35', '3', '7', '1'),
('36', 'Explique su respuesta', '', '1', '35', '1', '7', '1'),
('37', 'La experiencia influye(ó) en la asignación de recursos públicos del gobierno?', 'Califique de 1 a 5 (siendo 1 la menor y 5 la mayor)', '1', '37', '3', '7', '1'),
('38', 'Explique su respuesta', '', '1', '37', '1', '7', '1'),
('39', '¿La experiencia fomenta(ó) la cooperación entre los miembros de la organización', 'Califique de 1 a 5 (siendo 1 la menor y 5 la mayor)', '1', '39', '3', '8', '1'),
('40', 'Explique su respuesta', '', '1', '39', '1', '8', '1'),
('41', '¿La experiencia fomenta(ó) la creación o consolidación de vínculos y asociatividad entre las organizaciones de base?', 'Califique de 1 a 5 (siendo 1 la menor y 5 la mayor)', '1', '41', '3', '8', '1'),
('42', 'Explique su respuesta', '', '1', '41', '1', '8', '1'),
('43', '¿La experiencia fomenta(ó) la creación o consolidación de vínculos y asociatividad entre las organizaciones de base y con otros actores civiles, públicos o privados?', 'Califique de 1 a 5 (siendo 1 la menor y 5 la mayor)', '1', '43', '3', '8', '1'),
('44', 'Explique su respuesta', '', '1', '43', '1', '8', '1'),
('45', '¿La experiencia sirve(ió) de puente entre la comunidad y el gobierno local?', 'Califique de 1 a 5 (siendo 1 la menor y 5 la mayor)', '1', '45', '3', '8', '1'),
('46', 'Explique su respuesta', '', '1', '45', '1', '8', '1'),
('47', '¿La experiencia contribuye(ó) a ampliar la confianza entre la comunidad y otros actores?', 'Califique de 1 a 5 (siendo 1 la menor y 5 la mayor)', '1', '47', '3', '8', '1'),
('48', 'Explique su respuesta', '', '1', '47', '1', '8', '1'),
('49', 'Utilizar información sobre su entorno para diseñar y ejecutar experiencias', '', '1', '49', '3', '9', '1'),
('50', 'Explique su respuesta', '', '1', '49', '1', '9', '1'),
('51', 'Planear y formular proyectos', '', '1', '51', '3', '9', '1'),
('52', 'Explique su respuesta', '', '1', '51', '1', '9', '1'),
('53', 'Hacer seguimiento a las actividades y resultados', '', '1', '53', '3', '9', '1'),
('54', 'Explique su respuesta', '', '1', '53', '1', '9', '1'),
('55', 'Evaluar los resultados, analizar y ajustar las actividades y estrategias', '', '1', '55', '3', '9', '1'),
('56', 'Explique su respuesta', '', '1', '55', '1', '9', '1'),
('57', 'Administrar recursos', '', '1', '57', '3', '9', '1'),
('58', 'Explique su respuesta', '', '1', '57', '1', '9', '1'),
('59', 'Acceder a nuevas fuentes de recursos', '', '1', '59', '3', '9', '1'),
('60', 'Explique su respuesta', '', '1', '59', '1', '9', '1'),
('61', 'Negociar y resolver conflictos', '', '1', '61', '3', '9', '1'),
('62', 'Explique su respuesta', '', '1', '61', '1', '9', '1'),
('63', 'Acceder a espacios de participación', '', '1', '63', '3', '9', '1'),
('64', 'Explique su respuesta', '', '1', '63', '1', '9', '1'),
('65', '¿La experiencia contribuye(ó) a disminuir las condiciones de pobreza en la comunidad?', 'Califique de 1 a 5 (siendo 1 la menor y 5 la mayor)', '1', '65', '3', '10', '1'),
('66', 'Explique su respuesta', '', '1', '65', '1', '10', '1'),
('67', 'Suministre resultados cuantitativos o cualitativos para sustentar las transformaciones observadas en cuanto a disminución de la pobreza', '', '1', '67', '1', '10', '1'),
('68', '¿La experiencia contribuye(ó) a la profundización de la democracia?', 'Califique de 1 a 5 (siendo 1 la menor y 5 la mayor)', '1', '68', '3', '11', '1'),
('69', 'Explique su respuesta', '', '1', '68', '1', '11', '1'),
('70', 'Mencione datos o hechos ejemplifiquen los resultados', '', '1', '70', '1', '11', '1'),
('71', 'Si desea resaltar algún aspecto de la experiencia, utilice este espacio', '', '1', '71', '1', '5', '1'),
('72', 'Si desea anexar información, hágalo aquí', '', '1', '72', '1', '5', '1');